In [1]:
import torch
smooth_scales = torch.load("act_scales/llama2-7b-hf-smooth.pt")
act_scales = torch.load("act_scales/llama2-7b-hf-static.pt")
smooth_act_scales = torch.load("act_scales/llama2-7b-hf-smooth-static.pt")

In [3]:
for keys in act_scales.keys():
    print(keys)
    print(smooth_scales[keys])
    print(act_scales[keys]['input'])
    # print(smooth_act_scales[keys]['input'])

model.layers.0.self_attn.q_proj
tensor([0.1150, 0.0492, 0.0074,  ..., 0.0454, 0.0440, 0.0233])
tensor([[4.6719],
        [2.6406],
        [4.9727],
        ...,
        [4.9727],
        [4.9727],
        [4.9727]], device='cuda:0', dtype=torch.float16)
model.layers.0.self_attn.k_proj
tensor([0.1150, 0.0492, 0.0074,  ..., 0.0454, 0.0440, 0.0233])
tensor([[4.6719],
        [2.6406],
        [4.9727],
        ...,
        [4.9727],
        [4.9727],
        [4.9727]], device='cuda:0', dtype=torch.float16)
model.layers.0.self_attn.v_proj
tensor([0.1150, 0.0492, 0.0074,  ..., 0.0454, 0.0440, 0.0233])
tensor([[4.6719],
        [2.6406],
        [4.9727],
        ...,
        [4.9727],
        [4.9727],
        [4.9727]], device='cuda:0', dtype=torch.float16)
model.layers.0.self_attn.o_proj
tensor([0.0190, 0.0349, 0.0243,  ..., 0.0142, 0.0164, 0.0158])
tensor([[1.2568],
        [1.0771],
        [0.9146],
        ...,
        [0.4290],
        [0.4287],
        [0.4290]], device='cuda:0', d